server:
  port: 6060    #服务端口号为 6060
eureka:
  instance:
    hostname: localhost #主机名
  client:
    registerWithEureka: false #禁止注册中心注册自己
    fetchRegistry: false      #禁止检索服务
    healthcheck:
      enabled: true #健康检查开启
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #注册中心地址