eureka:
  client:
    healthcheck:
      enabled: true #健康检查开启
    service-url:
      defaultZone: http://localhost:6060/eureka/  #注册中心服务地址
server:
  port: 6050
spring:
  application:
    name: zuul
  #zuul:
  #  routes:
  