eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6060/eureka/  #注册中心服务地址
server:
  port: 7040  #当前服务端口
spring:
  application:
    name: service-consumer-ribbon-hystrix    #当前服务ID
  zipkin:
    base-url: http://localhost:6040 #zipkin服务地址