eureka:
  client:
    healthcheck:
      enabled: true #健康检查开启
    service-url:
      defaultZone: http://localhost:6060/eureka/
server:
  port: 6010
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wkedong/Spring-Cloud-Config.git